CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name TEXT NOT NULL , user_role TEXT NOT NULL , phone_number NUMERIC NOT NULL, password TEXT NOT NULL);

CREATE TABLE bookings(user_id INTEGER , room_type TEXT NOT NULL , duration integer NOT NULL,date DATETIME DEFAULT CURRENT_TIMESTAMP ,price NUMERIC NOT NULL,total NUMERIC NOT NULL ,FOREIGN KEY (user_id) REFERENCES users(id));

CREATE TABLE services(user_id INTEGER, laundry INTEGER DEFAULT  0 , swimming INTEGER DEFAULT 0, food INTEGER DEFAULT 0,gyming INTEGER DEFAULT 0 , massage INTEGER DEFAULT 0,date DATETIME DEFAULT CURRENT_TIMESTAMP, expenses INTEGER NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));




